### ISSUE TITLE
Error in production on vue, vite

### ISSUE THREAD

**Issue by gkucmierz** [qrohlf/trianglify#158]
```
index-VkoFY4_Q.js:1 TypeError: Uv is not a function
    at i (index-VkoFY4_Q.js:56:54894)
    at index-VkoFY4_Q.js:1:23734
    at Dt (index-VkoFY4_Q.js:1:13199)
    at ot (index-VkoFY4_Q.js:1:13278)
    at Dn.t.__weh.t.__weh (index-VkoFY4_Q.js:1:23614)
    at zi (index-VkoFY4_Q.js:1:14593)
    at Jr (index-VkoFY4_Q.js:1:43511)
    at mount (index-VkoFY4_Q.js:1:30249)
    at G0.t.mount (index-VkoFY4_Q.js:1:58816)
    at index-VkoFY4_Q.js:56:55329
```

**Comment by Samuel-BlankAmber** [comment]
Encountering a similar issue when using Vite, albeit not with Vue.
My error is related to this line. The `from` function is not found.
```js
var geomIndices = Delaunator.from(points).triangles;
```

I suspect it's related to this function:
```js
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var Delaunator = _interopDefault(require('delaunator'));
```

`typeof ex` evaluates to `'function'`. Not sure why, but it causes issues. Changing it to this fixes it:
```js
var Delaunator = require('delaunator').default || require('delaunator');
```
